[package]
name = "gpt-rs-c-runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gpt-rs = { path = "../gpt-rs" }
gpt-rs-backend-ref-cpu = { path = "../gpt-rs-backend-ref-cpu" }
serde_json = { workspace = true }
